name: 'Test Summary Action'
description: 'Create a test report and outputs it on GitHub summary'
author: 'Factorial'
inputs:
  engine:
    required: true
    description: 'Test Engine to compute the summary (cypress)'
  reportFile:
    required: true
    description: 'Test report file provided by the test runner'
  sha:
    required: true
    description: 'The commit SHA that triggered the action'
  s3AccessKey:
    required: true
    description: 'The AWS Access key credential'
  s3SecretKey:
    required: true
    description: 'The AWS Secret key credential'
runs:
  using: 'node16'
  main: 'dist/index.js'
