name: "Test Summary Action"
description: "Create a test report and outputs it on GitHub summary"
author: "Factorial"
inputs:
  engine:
    required: true
    description: "Test Engine to compute the summary (cypress)"
  reportFile:
    required: true
    description: "Test report file provided by the test runner"
  sha:
    required: true
    description: "The commit SHA that triggered the action"
  s3BucketName:
    required: false
    description: "[Cypress only] The S3 bucket name where screenshots are stored (it must be public)"
  s3Region:
    required: false
    description: "[Cypress only] The AWS region where the bucket belongs to"
runs:
  using: "node16"
  main: "dist/index.js"
